### ISSUE TITLE
Login case sensitivity

### ISSUE THREAD

**Issue by Aithr-13** [skotikus/SDEV495_Group5#4]
It seems like logins are not case sensitive despite our test passwords potentially provoking case sensitivity issues on the backend. 

Instructions to reproduce: 
Login with "testpass" instead of "TestPass" will provide successful login

Suspect this has something to do with how index.jsp and authenticate.java are interacting, around line 85 in authenticate.java.

**Comment by skotikus** [comment]
Found the issue:
Maria DB UTF8 character set is case-insensitive by default. (cite: https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html)



Changing Authenticate.java line 135 to this fixes the issue:
String sql2 = "select user_id from user_info where user_id = " + user_id + " and password COLLATE utf8_bin = '" + this.pword + "'";
